name: Converter HTML para APK

on:
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      # Correção do bug: Cria uma pasta separada e joga o index.html nela
      - name: Organizar arquivos para o Build
        run: |
          mkdir pasta_app
          cp index.html pasta_app/

      - name: Criar APK a partir do HTML
        uses: darkshredder/web-to-app-action@main
        with:
          build-folder-path: "pasta_app"   # Agora ele lê a pasta isolada sem dar loop
          app-name: "MeuApp"               # Digite aqui o nome do seu aplicativo
          output-folder-path: "output"

      - name: Disponibilizar APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: Aplicativo-APK
          path: output/
